export enum EnumErrorCode
{
	VALIDATION_ERROR = 'VALIDATION_ERROR',
	REQUEST_FAILED = 'REQUEST_FAILED',
	TRANSFORMATION_ERROR = 'TRANSFORMATION_ERROR',
	PARSE_ERROR = 'PARSE_ERROR',
	DOWNLOAD_FAILED = 'DOWNLOAD_FAILED',
}
